"""init tables

Revision ID: 3b433d6566d1
Revises: 
Create Date: 2026-02-16 12:33:13.701780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b433d6566d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('write_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    sync_state = op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('write_date', sa.DateTime()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        sync_state,
        [
            {
                "id": 1,
                "model": "res.partner",
                "write_date": None
            }
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    op.drop_table('partners')
    # ### end Alembic commands ###
