"""Adding reconciliation flag for reconciliation job

Revision ID: 966b79453ddf
Revises: 3b433d6566d1
Create Date: 2026-02-16 16:57:10.309601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966b79453ddf'
down_revision: Union[str, Sequence[str], None] = '3b433d6566d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('reconciliation_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'reconciliation_flag')
    # ### end Alembic commands ###
