"""Separated odoo_id and internal db id _ fix repr

Revision ID: f0a4e79cf42d
Revises: 966b79453ddf
Create Date: 2026-02-18 00:12:21.723835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a4e79cf42d'
down_revision: Union[str, Sequence[str], None] = '966b79453ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('odoo_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_partners_odoo_id'), 'partners', ['odoo_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partners_odoo_id'), table_name='partners')
    op.drop_column('partners', 'odoo_id')
    # ### end Alembic commands ###
